openapi: "3.0.3"
info:
  version: 1.0.0
  title: Lovvalg og medlemskap
servers:
  - url: https://medlemskap-oppslag.nais.preprod.local
    description: preproduksjon
  - url: https://medlemskap-oppslag.nais.adeo.no
    description: produksjon
paths:
  /:
    post:
      summary: Avgjøre om lovvalg er norsk, og om bruker er medlem av folketrygden
      operationId: avgjørLovvalgOgMedlemskap
      security:
        - oAuth2:
          - api://<client_id>/.default
      tags:
        - Lovvalg
        - Medlemskap
      description: Expected response to a valid request
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Request"
      responses:
        200:
          description: Forventet response på en gyldig request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        400:
          description: Ugyldig request eller annen feil
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
          scopes:
            api://<client_id>/:default: client tilgang
  schemas:
    Adresse:
      properties:
        landkode:
          $ref: "#/components/schemas/Landkode"
        fom:
          $ref: "#/components/schemas/ValgfriDato"
        tom:
          $ref: "#/components/schemas/ValgfriDato"
    Ansatte:
      properties:
        antall:
          type: integer
          nullable: true
        bruksperiode:
          $ref: "#/components/schemas/Bruksperiode"
        gyldighetsperiode:
          $ref: "#/components/schemas/Gyldighetsperiode"
    Arbeidsavtale:
      properties:
        periode:
          $ref: "#/components/schemas/Periode"
        gyldighetsperiode:
          $ref: "#/components/schemas/Periode"
        yrkeskode:
          type: string
        skipsregister:
          type: string
          nullable: true
        stillingsprosent:
          type: number
          multipleOf: 0.01
          nullable: true
        beregnetAntallTimerPrUke:
          type: number
          multipleOf: 0.01
          nullable: true
    Arbeidsforhold:
      properties:
        periode:
          $ref: "#/components/schemas/Periode"
        utenlandsopphold:
          type: array
          items:
            $ref: "#/components/schemas/Utenlandsopphold"
        arbeidsgivertype:
          type: string
          enum:
            - Organisasjon
            - Person
        arbeidsgiver:
          $ref: "#/components/schemas/Arbeidsgiver"
        arbeidsforholdstype:
          type: string
          enum:
            - FRILANSER
            - MARITIM
            - NORMALT
            - FORENKLET
            - ANDRE
        arbeidsavtaler:
          type: array
          items:
            $ref: "#/components/schemas/Arbeidsavtale"
    Arbeidsgiver:
      properties:
        type:
          type: string
          nullable: true
        organisasjonsnummer:
          type: string
          nullable: true
        ansatte:
          type: array
          items:
            $ref: "#/components/schemas/Ansatte"
          nullable: true
        konkursStatus:
          type: array
          items:
            type: string
          nullable: true
        juridiskEnhetEnhetstypeMap:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/JuridiskEnhetstype"
          nullable: true
    BrukerInput:
      properties:
        arbeidUtenforNorge:
          type: boolean
    Bruksperiode:
      properties:
        fom:
          $ref: "#/components/schemas/ValgfriDato"
        tom:
          $ref: "#/components/schemas/ValgfriDato"
      nullable: true
    Code:
      properties:
        value:
          type: integer
        description:
          type: string
    Datagrunnlag:
      properties:
        periode:
          $ref: "#/components/schemas/InputPeriode"
        brukerinput:
          $ref: "#/components/schemas/BrukerInput"
        pdlpersonhistorikk:
          $ref: "#/components/schemas/Personhistorikk"
        medlemskap:
          type: array
          items:
            $ref: "#/components/schemas/Medlemskap"
        arbeidsforhold:
          type: array
          items:
            $ref: "#/components/schemas/Arbeidsforhold"
        oppgaver:
          type: array
          items:
            $ref: "#/components/schemas/Oppgave"
        dokument:
          type: array
          items:
            $ref: "#/components/schemas/Journalpost"
        ytelse:
          type: string
          example: SYKEPENGER, DAGPENGER, ENSLIG_FORSORGER
        dataOmBarn:
          type: array
          items:
            $ref: "#/components/schemas/DataOmBarn"
          nullable: true
        dataOmEktefelle:
          $ref: "#/components/schemas/DataOmEktefelle"
    DataOmBarn:
      properties:
        personhistorikkBarn:
          $ref: "#/components/schemas/PersonhistorikkBarn"
    DataOmEktefelle:
      properties:
        personhistorikkEktefelle:
          $ref: "#/components/schemas/PersonhistorikkEktefelle"
        arbeidsforholdEktefelle:
          type: array
          items:
            $ref: "#/components/schemas/Arbeidsforhold"
      nullable: true
    Delresultat:
      type: array
      items:
        $ref: "#/components/schemas/Resultat"
    Dato:
      type: string
      format: date
      description: Dato
      nullable: true
      example: "2021-01-30"
    Dokument:
      properties:
        dokumentId:
          type: string
        tittel:
          type: string
          nullable: true
    Error:
      required:
        - url
        - message
      properties:
        url:
          type: string
        message:
          type: string
        cause:
          type: string
        code:
          $ref: "#/components/schemas/Code"
    Familierelasjon:
      properties:
        relatertPersonsIdent:
          type: string
        relatertPersonsRolle:
          type: string
        minRolleForPerson:
          type: string
          nullable: true
        folkeregistermetadata:
          $ref: "#/components/schemas/Folkeregistermetadata"
    Folkeregistermetadata:
      properties:
        ajourholdstidspunkt:
          $ref: "#/components/schemas/ValgfriDatoTid"
        gyldighetstidspunkt:
          $ref: "#/components/schemas/ValgfriDatoTid"
        opphoerstidspunkt:
          $ref: "#/components/schemas/ValgfriDatoTid"
      nullable: true
    FolkeregisterPersonstatus:
      properties:
        personstatus:
          type: string
        fom:
          $ref: "#/components/schemas/ValgfriDato"
        tom:
          $ref: "#/components/schemas/ValgfriDato"
    Doedsfall:
        type: array
        items:
          $ref: "#/components/schemas/ValgfriDato"
    Gyldighetsperiode:
      properties:
        fom:
          $ref: "#/components/schemas/ValgfriDato"
        tom:
          $ref: "#/components/schemas/ValgfriDato"
      nullable: true
    InputPeriode:
      properties:
        fom:
          $ref: "#/components/schemas/ValgfriDato"
        tom:
          $ref: "#/components/schemas/ValgfriDato"
    Journalpost:
      properties:
        journalpostId:
          type: string
        tittel:
          type: string
          nullable: true
        journalposttype:
          type: string
          nullable: true
        journalstatus:
          type: string
          nullable: true
        tema:
          type: string
          nullable: true
        dokumenter:
          type: array
          items:
            $ref: "#/components/schemas/Dokument"
          nullable: true
    JuridiskEnhetstype:
      type: string
    Landkode:
      type: string
      minLength: 2
      maxLength: 3
      description: Landkode med to eller tre tegn
      example: NOR
    Medlemskap:
      properties:
        dekning:
          type: string
          nullable: true
        fraOgMed:
          $ref: "#/components/schemas/Dato"
        tilOgMed:
          $ref: "#/components/schemas/Dato"
        erMedlem:
          type: boolean
        lovvalg:
          type: string
          nullable: true
        lovvalgsland:
          type: string
          nullable: true
        periodeStatus:
          type: string
          nullable: true
    Oppgave:
      properties:
        aktivDato:
          $ref: "#/components/schemas/Dato"
        prioritet:
          type: string
          enum:
            - HOY
            - NORM
            - LAV
        status:
          type: string
          enum:
            - OPPRETTET
            - AAPNET
            - UNDER_BEHANDLING
            - FERDIGSTILT
            - FEILREGISTRERT
        tema:
          type: string
          nullable: true
    Periode:
      properties:
        fom:
          $ref: "#/components/schemas/ValgfriDato"
        tom:
          $ref: "#/components/schemas/ValgfriDato"
    Personhistorikk:
      properties:
        statsborgerskap:
          type: array
          items:
            $ref: "#/components/schemas/Statsborgerskap"
        personstatuser:
          type: array
          items:
            $ref: "#/components/schemas/FolkeregisterPersonstatus"
        bostedsadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        kontaktadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        oppholdsadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        sivilstand:
          type: array
          items:
            $ref: "#/components/schemas/Sivilstand"
        familierelasjoner:
          type: array
          items:
            $ref: "#/components/schemas/Familierelasjon"
        doedsfall:
          type: array
          items:
            $ref: "#/components/schemas/ValgfriDato"
    PersonhistorikkBarn:
      properties:
        ident:
          type: string
        bostedsadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        kontaktadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        oppholdsadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        familierelasjoner:
          type: array
          items:
            $ref: "#/components/schemas/Familierelasjon"
    PersonhistorikkEktefelle:
      properties:
        ident:
          type: string
        barn:
          type: array
          nullable: true
          items:
            type: string
        bostedsadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        kontaktadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
        oppholdsadresser:
          type: array
          items:
            $ref: "#/components/schemas/Adresse"
    Request:
      properties:
        fnr:
          type: string
        periode:
          $ref: "#/components/schemas/InputPeriode"
        brukerinput:
          $ref: "#/components/schemas/BrukerInput"
    Response:
      properties:
        datagrunnlag:
          $ref: "#/components/schemas/Datagrunnlag"
        resultat:
          $ref: "#/components/schemas/Resultat"
        versjonRegler:
          type: string
        tidspunkt:
          type: string
        versjonTjeneste:
          type: string
    Resultat:
      required:
        - regelId
        - avklaring
        - begrunnelse
        - svar
      properties:
        regelId:
          type: string
          description: Identifiserer en regel
        avklaring:
          type: string
          description: Spørsmål som regelen avklarer
        begrunnelse:
          type: string
          description: Begrunnelse for avklaringen
        svar:
          type: string
          enum:
            - JA
            - NEI
            - UAVKLART
        harDekning:
          type: string
          nullable: true
          description: Har den angitte ytelsen dekning?
        dekning:
          type: string
          description: Angir hva slags dekning brukeren har ifølge Folketrygdloven
          example: FTL_2-6
        delresultat:
          type: array
          items:
            $ref: "#/components/schemas/Resultat"
    Sivilstand:
      properties:
        type:
          type: string
        gyldigFraOgMed:
          $ref: "#/components/schemas/ValgfriDato"
        gyldigTilOgMed:
          $ref: "#/components/schemas/ValgfriDato"
        relatertVedSivilstand:
          type: string
          nullable: true
        folkeregistermetadata:
          $ref: "#/components/schemas/Folkeregistermetadata"
    Statsborgerskap:
        properties:
          landkode:
            $ref: "#/components/schemas/Landkode"
          fom:
            $ref: "#/components/schemas/ValgfriDato"
          tom:
            $ref: "#/components/schemas/ValgfriDato"
    Utenlandsopphold:
      properties:
        landkode:
          $ref: "#/components/schemas/Landkode"
        periode:
          $ref: "#/components/schemas/ValgfriPeriode"
        rapporteringsperiode:
          type: string
          example: 2015-02
      nullable: true
    ValgfriDato:
      type: string
      format: date
      description: Dato
      nullable: true
      example: "2021-01-30"
    ValgfriDatoTid:
      type: string
      description: Dato tid
      nullable: true
      example: "2021-01-30T17:32:28"
    ValgfriPeriode:
      properties:
        fom:
          $ref: "#/components/schemas/ValgfriDato"
        tom:
          $ref: "#/components/schemas/ValgfriDato"
      nullable: true