apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-oppslag
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  image: {{ image }}
  port: 7070
  liveness:
    path: isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://medlemskap-oppslag.nais.preprod.local
    - https://medlemskap-oppslag.dev.adeo.no
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/medlemskap-oppslag/default
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /azuread/data/dev/creds/medlemskap-oppslag
  secureLogs:
    enabled: true
  webproxy: true

  env:
    - name: AZURE_TENANT
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw-q1.oera.no//SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
    - name: TPSWS_URL
      value: https://api-gw-q1.oera.no/tpsws/ws/Person/v3
    - name: INNTEKT_BASE_URL
      value: https://api-gw-q1.oera.no/inntektskomponenten-ws
    - name: MEDL2_BASE_URL
      value: https://api-gw-q1.oera.no/medl2
    - name: AAREG_BASE_URL
      value: https://api-gw-q1.oera.no/aareg-services/api
    - name: SAF_BASE_URL
      value: http://api-gw-q1.oera.no/graphql
    - name: OPPGAVE_BASE_URL
      value: https://api-gw-q1.oera.no/oppgave
    - name: PDL_BASE_URL
      value: http://api-gw-q1.oera.no/graphql
    - name: EREG_BASE_URL
      value: https://api-gw-q1.oera.no/ereg/api
    - name: UDI_BASE_URL
      value: https://pep-gw-q1.oera-q.local:9443/ekstern/udi/personstatus/medlemskapoppslag/v1
