apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-oppslag
  namespace: default
  labels:
    team: medlemskap
spec:
  image: {{ image }}
  port: 7070
  liveness:
    path: isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://medlemskap-oppslag.nais.preprod.local
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/medlemskap-oppslag/default
  webproxy: true

  env:
    - name: AZURE_TENANT
      value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
    - name: AZURE_AUTHORITY_ENDPOINT
      value: https://login.microsoftonline.com
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: TPSWS_URL
      value: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
