apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: medlemskap-oppslag
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  image: {{ image }}
  port: 7070
  liveness:
    path: isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://medlemskap-oppslag.dev.intern.nav.no
    - https://medlemskap-oppslag.dev.nav.no
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  webproxy: true
  kafka:
    pool: nav-dev

  accessPolicy:
    inbound:
      rules:
        - application: medlemskap-oppslag
        - application: medlemskap-oppslag-funksjonelle-tester
        - application: medlemskap-sykepenger-listener
        - application: medlemskap-dagpengelytter
        - application: sparkel-medlemskap
          namespace: tbd
          cluster: dev-fss
        - application: hm-brille-api
          namespace: teamdigihot
          cluster: dev-gcp
    outbound:
      rules:
        - application: udi-proxy
          namespace: medlemskap
          cluster: dev-fss
      external:
        - host: api-gw-q1.oera.no
        - host: api-gw-q2.oera.no
        - host: saf.dev-fss-pub.nais.io
        - host: login.microsoftonline.com
        - host: udi-proxy.dev-fss-pub.nais.io
        - host: aareg-services-q1.dev-fss-pub.nais.io
        - host: ereg-services.dev.intern.nav.no
  env:
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://api-gw-q1.oera.no/sts/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://api-gw-q1.oera.no/security-token-service
    - name: MEDL2_BASE_URL
      value: https://api-gw-q2.oera.no/medlemskap-medl-api
    - name: AAREG_BASE_URL
      value: https://aareg-services-q1.dev-fss-pub.nais.io/api
    - name: SAF_BASE_URL
      value: https://saf.dev-fss-pub.nais.io/graphql
    - name: OPPGAVE_BASE_URL
      value: https://api-gw-q1.oera.no/oppgave
    - name: PDL_BASE_URL
      value: https://api-gw-q1.oera.no/pdl-api/graphql
    - name: EREG_BASE_URL
      value: https://api-gw-q1.oera.no/ereg-services/api
    - name: UDI_BASE_URL
      value: https://udi-proxy.dev-fss-pub.nais.io
  envFrom:
    - secret: medlemskap-oppslag